/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aAH7BbEMapRwdaNzVKJpgK

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: aAH7BbEMapRwdaNzVKJpgK/projectModule

const data = {
  base: `${"plasmic_tokens_aAH7BbEMapRwdaNzVKJpgK"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
